export enum ActionType {
  FETCH_APPS_COMPLETED = 'FETCH_APPS_COMPLETED',
  SELECT_APP = 'SELECT_APP',
  SELECT_APP_TARGET = 'SELECT_APP_TARGET',
  FETCH_REGISTIES_COMPLETED = 'FETCH_REGISTRIES_COMPLETED',
  SELECT_REGISRY = 'SELECT_REGISTRY',
  FETCH_REGISTRY_DATA_COMPLETED = 'FETCH_REGISTRY_DATA_COMPLETED'
};