export enum ActionType {
  FETCH_APPS_COMPLETED = 'FETCH_APPS_COMPLETED',
  SELECT_APP = 'SELECT_APP',
  SELECT_APP_TARGET = 'SELECT_APP_TARGET',
  FETCH_REGISTIES_COMPLETED = 'FETCH_REGISTRIES_COMPLETED',
  CLEAR_REGISTIES = 'CLEAR_REGISTRIES',
  SELECT_REGISRY = 'SELECT_REGISTRY',
  FETCH_REGISTRY_DATA_COMPLETED = 'FETCH_REGISTRY_DATA_COMPLETED',
  PING_APPS_COMPLETED = 'PING_APPS_COMPLETED',
  FETCH_CONFIG_PROPERTIES_COMPLETED = 'FETCH_CONFIG_PROPERTIES_COMPLETED'
};